spring:
  profiles:
    active: test
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    url: ${FLYWAY_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    enabled: ${FLYWAY_ENABLED:true}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    : ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:WARN}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    try-it-out-enabled: ${SWAGGER_ENABLED:false}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,info}
  endpoint:
    health:
      show-details: ${HEALTH_DETAILS:when-authorized}