apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springboot-application-mapper
  description: MapStruct mappers for entity transformations for Spring Boot template
  tags:
    - application
    - mapper
    - mapstruct
    - hexagonal-architecture
  annotations:
    github.com/project-slug: addon-ai/backstage-templates
spec:
  type: library
  owner: platform-team
  lifecycle: production
  subcomponentOf: component:default/springboot-application-layer
